language: python
os:
  - linux
notifications:
  email: false
before_install:
  - pip install --quiet tox
script:

  # Create an environment first so that we know what to use for $PYTHON:
  - tox --notest

  # PyCall requires to know the right Python executable to use:
  - export PYTHON="$(echo $PWD/.tox/py*/bin/python)"
  - echo "$PYTHON"

  - tox -- --cov diffeqpy
jobs:
  include:
    - env: TOXENV=py3
      python: "3.8"
    - env: TOXENV=py3-numba
      python: "3.8"
  allow_failures:
    - env: TOXENV=py3-numba
